### ISSUE TITLE
Productize Gradle Plugin Analyzer and publish as a plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [lptr/gradle-plugin-analyzer#28]
The usage of internal APIs is one of the root causes of compatibility issues in Gradle plugins and build script definitions. The plugin analyzer already has an internal logic that enables checks by scanning bytecode. It would be nice to productize this functionality and make it available to Gradle plugin developers and, ideally, to developers of build definitions.

## TODO

- [ ] Add options that allow scanning of the Gradle plugin project with the scanner
- [ ] Finalize the documentation to reflect the current behavior
- [ ] Finalize build definitions to enable plugin publishing to Gradle Plugin Portal
- [ ] Add necessary parameters to use a standalone scanner outside of the repository

## Nice to have

- [ ] Better documentation for using in GitHub actions 
- [ ] Enable self-scanning of build scripts
